M48
; DRILL file {KiCad 9.0.1} date 2025-08-05T19:10:54+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-05T19:10:54+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X136.77Y-92.375
X142.55Y-92.375
T2
X100.0Y-90.0
X100.0Y-120.0
X150.0Y-90.0
X150.0Y-120.0
M30
